//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClassModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public Nullable<bool> DeletionFlag { get; set; }
        public string AppOrderNum { get; set; }
    
        public virtual Divisions Divisions { get; set; }
        public virtual Employes Employes { get; set; }
        public virtual Positions Positions { get; set; }
    }
}
