//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClassModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyInfo
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAdress { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyPhine { get; set; }
        public string CompanyEDRP { get; set; }
        public Nullable<int> CompanyHeadId { get; set; }
        public Nullable<int> CompanyHRHeadId { get; set; }
        public Nullable<int> CompanyFinHeadId { get; set; }
    
        public virtual Employes Employes { get; set; }
        public virtual Employes Employes1 { get; set; }
        public virtual Employes Employes2 { get; set; }
    }
}
