//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClassModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRWorkEntities : DbContext
    {
        public HRWorkEntities()
            : base("name=HRWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<Divisions> Divisions { get; set; }
        public virtual DbSet<EduLevels> EduLevels { get; set; }
        public virtual DbSet<Employes> Employes { get; set; }
        public virtual DbSet<FireCauses> FireCauses { get; set; }
        public virtual DbSet<Fires> Fires { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Salaries> Salaries { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfo { get; set; }
        public virtual DbSet<Vacations> Vacations { get; set; }
        public virtual DbSet<GeneralOrders> GeneralOrders { get; set; }
    }
}
