//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataClassModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacations
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> VacationDays { get; set; }
    
        public virtual Employes Employes { get; set; }
    }
}
